### ISSUE TITLE
Flaky createTimeSeries endpoint

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/nodejs-monitoring#191]
The `client.createTimeSeries` API endpoint appears to be very, very flaky.  In the tests, we had to implement retry logic to work around this error:

```
Write failed, retrying...
{ Error: 13 INTERNAL: One or more TimeSeries could not be written: An internal error occurred.: timeSeries[0]
    at Object.exports.createStatusError (/Users/beckwith/Code/nodejs-monitoring/samples/node_modules/grpc/src/common.js:91:15)
    at Object.onReceiveStatus (/Users/beckwith/Code/nodejs-monitoring/samples/node_modules/grpc/src/client_interceptors.js:1204:28)
    at InterceptingListener._callNext (/Users/beckwith/Code/nodejs-monitoring/samples/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/Users/beckwith/Code/nodejs-monitoring/samples/node_modules/grpc/src/client_interceptors.js:618:8)
    at callback (/Users/beckwith/Code/nodejs-monitoring/samples/node_modules/grpc/src/client_interceptors.js:845:24)
  code: 13,
  metadata: Metadata { _internal_repr: {} },
  details:
   'One or more TimeSeries could not be written: An internal error occurred.: timeSeries[0]' }
```

This is happening in our quickstart, which is super sad:
```js
// [START monitoring_quickstart]
// Imports the Google Cloud client library
const monitoring = require('@google-cloud/monitoring');

async function quickstart() {
  // Your Google Cloud Platform project ID
  const projectId = process.env.GCLOUD_PROJECT || 'YOUR_PROJECT_ID';

  // Creates a client
  const client = new monitoring.MetricServiceClient();

  // Prepares an individual data point
  const dataPoint = {
    interval: {
      endTime: {
        seconds: Date.now() / 1000,
      },
    },
    value: {
      // The amount of sales
      doubleValue: 123.45,
    },
  };

  // Prepares the time series request
  const request = {
    name: client.projectPath(projectId),
    timeSeries: [
      {
        // Ties the data point to a custom metric
        metric: {
          type: 'custom.googleapis.com/stores/daily_sales',
          labels: {
            store_id: 'Pittsburgh',
          },
        },
        resource: {
          type: 'global',
          labels: {
            project_id: projectId,
          },
        },
        points: [dataPoint],
      },
    ],
  };

  // Writes time series data
  const [result] = await client.createTimeSeries(request);
  console.log(`Done writing time series data.`, result);
}
// [END monitoring_quickstart]

quickstart().catch(console.error);
```

**Comment by JustinBeckwith** [comment]
This appears to magically be fixed.
