### ISSUE TITLE
Sample tests are flaking

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/nodejs-monitoring#359]
looking at https://github.com/googleapis/nodejs-monitoring/pull/358, there's no reason the sample tests should be failing.

**Comment by JustinBeckwith** [comment]
These appear to be outright failing now:
```
23 passing (42s)
  1 failing

  1) metrics
       should read time series data aggregated:
     Command failed: node metrics.js read-aggregate
metrics.js read-aggregate [projectId]

Aggregates time series data that matches 'compute.googleapis.com/instance/cpu/utilization'.

Options:
  --version        Show version number                                                                         [boolean]
  --projectId, -p                                                                    [string] [default: "long-door-651"]
  --help           Show help                                                                                   [boolean]

TypeError: Cannot read property 'value' of undefined
    at timeSeries.forEach.data (/tmpfs/src/github/nodejs-monitoring/samples/metrics.js:328:49)
    at Array.forEach (<anonymous>)
    at readTimeSeriesAggregate (/tmpfs/src/github/nodejs-monitoring/samples/metrics.js:325:14)
    at process._tickCallback (internal/process/next_tick.js:68:7)

  Error: Command failed: node metrics.js read-aggregate
  metrics.js read-aggregate [projectId]

  Aggregates time series data that matches 'compute.googleapis.com/instance/cpu/utilization'.

  Options:
    --version        Show version number                                                                         [boolean]
    --projectId, -p                                                                    [string] [default: "long-door-651"]
    --help           Show help                                                                                   [boolean]

  TypeError: Cannot read property 'value' of undefined
      at timeSeries.forEach.data (metrics.js:328:49)
      at Array.forEach (<anonymous>)
      at readTimeSeriesAggregate (metrics.js:325:14)
      at process._tickCallback (internal/process/next_tick.js:68:7)

      at checkExecSyncError (child_process.js:629:11)
      at Object.execSync (child_process.js:666:13)
      at execSync (test/metrics.test.js:23:28)
      at Context.it (test/metrics.test.js:154:20)
      at process._tickCallback (internal/process/next_tick.js:68:7)



npm ERR! Test failed.  See above for more details.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @google-cloud/monitoring@1.7.0 samples-test: `cd samples/ && npm link ../ && npm install && npm test && cd ../`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @google-cloud/monitoring@1.7.0 samples-test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/node/.npm/_logs/2020-03-06T00_51_30_952Z-debug.log
cleanup
```

**Comment by bcoe** [comment]
closing in favor of https://github.com/googleapis/nodejs-monitoring/issues/382, we are actually tracking flaky tests now and we will treat each as a `p1`.
