### ISSUE TITLE
alert samples tests failures

### ISSUE THREAD

**Issue by alexander-fenster** [googleapis/nodejs-monitoring#43]
The following two samples tests fail in master:

  ✖ alerts › before Rejected promise returned by test
  ✖ alerts › after Rejected promise returned by test

Please investigate and fix.

cc: @crwilcox

**Comment by alexander-fenster** [comment]
They still fail :(

```
  2 tests failed

  alerts › before

  /var/monitoring/node_modules/grpc/src/common.js:87

  Rejected promise returned by test. Reason:

  Error {
    code: 3,
    details: 'Field alert_policy.conditions[0].condition_absent.filter had an invalid value of "metric.type = "cloudfunctions.googleapis.com/function/execution_count"": must specify a restriction on "resource.type" in the filter; see "https://cloud.google.com/monitoring/api/resources" for a list of available resource types.',
    metadata: Metadata {
      _internal_repr: {},
    },
    message: '3 INVALID_ARGUMENT: Field alert_policy.conditions[0].condition_absent.filter had an invalid value of "metric.type = "cloudfunctions.googleapis.com/function/execution_count"": must specify a restriction on "resource.type" in the filter; see "https://cloud.google.com/monitoring/api/resources" for a list of available resource types.',
  }

  Object.exports.createStatusError (/var/monitoring/node_modules/grpc/src/common.js:87:15)
  Object.onReceiveStatus (/var/monitoring/node_modules/grpc/src/client_interceptors.js:1214:28)
  InterceptingListener._callNext (/var/monitoring/node_modules/grpc/src/client_interceptors.js:590:42)
  InterceptingListener.onReceiveStatus (/var/monitoring/node_modules/grpc/src/client_interceptors.js:640:8)
  callback (/var/monitoring/node_modules/grpc/src/client_interceptors.js:867:24)



  alerts › after

  /var/monitoring/node_modules/grpc/src/common.js:87

  Rejected promise returned by test. Reason:

  Error {
    code: 3,
    details: 'Request was missing field name.',
    metadata: Metadata {
      _internal_repr: {},
    },
    note: 'Exception occurred in retry method that was not classified as transient',
    message: '3 INVALID_ARGUMENT: Request was missing field name.',
  }

  Object.exports.createStatusError (/var/monitoring/node_modules/grpc/src/common.js:87:15)
  Object.onReceiveStatus (/var/monitoring/node_modules/grpc/src/client_interceptors.js:1214:28)
  InterceptingListener._callNext (/var/monitoring/node_modules/grpc/src/client_interceptors.js:590:42)
  InterceptingListener.onReceiveStatus (/var/monitoring/node_modules/grpc/src/client_interceptors.js:640:8)
  callback (/var/monitoring/node_modules/grpc/src/client_interceptors.js:867:24)
```

**Comment by jmdobry** [comment]
What project are the tests using, perhaps it needs to enable the Cloud Functions API?

**Comment by alexander-fenster** [comment]
All tests in CI use `google-cloud-node` project (id `long-door-651`). Is there any special setup that needs to be done for these two tests?

**Comment by jmdobry** [comment]
Can you try this?

(you may need to set `GCLOUD_PROJECT` and `GOOGLE_APPLICATION_CREDENTIALS` env vars)

```
cd nodejs-monitoring/samples
node metrics.js list google-cloud-node | grep function
```

and print the output?

**Comment by jmdobry** [comment]
The out put I see for the `nodejs-docs-samples` project is:

```
$ node metrics list nodejs-docs-samples | grep function
projects/nodejs-docs-samples/metricDescriptors/cloudfunctions.googleapis.com/function/execution_count
projects/nodejs-docs-samples/metricDescriptors/cloudfunctions.googleapis.com/function/execution_times
projects/nodejs-docs-samples/metricDescriptors/cloudfunctions.googleapis.com/function/network_egress
projects/nodejs-docs-samples/metricDescriptors/cloudfunctions.googleapis.com/function/user_memory_bytes
```

**Comment by alexander-fenster** [comment]
You're right, it does not work for me (I get the same result: the alert tests fail and the other tests pass).

```
ERROR: { Error: 7 PERMISSION_DENIED: User is not authorized to access the project monitoring records: Permission denied.
    at Object.exports.createStatusError (/usr/local/google/home/fenster/nodejs-packages/nodejs-monitoring/node_modules/grpc/src/common.js:87:15)
    at Object.onReceiveStatus (/usr/local/google/home/fenster/nodejs-packages/nodejs-monitoring/node_modules/grpc/src/client_interceptors.js:1214:28)
    at InterceptingListener._callNext (/usr/local/google/home/fenster/nodejs-packages/nodejs-monitoring/node_modules/grpc/src/client_interceptors.js:590:42)
    at InterceptingListener.onReceiveStatus (/usr/local/google/home/fenster/nodejs-packages/nodejs-monitoring/node_modules/grpc/src/client_interceptors.js:640:8)
    at callback (/usr/local/google/home/fenster/nodejs-packages/nodejs-monitoring/node_modules/grpc/src/client_interceptors.js:867:24)
  code: 7,
  metadata: 
   Metadata {
     _internal_repr: 
      { 'google.rpc.debuginfo-bin': [Array],
        'grpc-status-details-bin': [Array] } },
  details: 'User is not authorized to access the project monitoring records: Permission denied.',
  note: 'Exception occurred in retry method that was not classified as transient' }
```

Do you know where in the console it should be fixed?

**Comment by jmdobry** [comment]
Try giving your service account the Monitoring Admin role
