### ISSUE TITLE
No such type: google.monitoring.v3.CreateTimeSeriesSummary

### ISSUE THREAD

**Issue by stx** [googleapis/nodejs-monitoring#566]
I'm not able to get this library to work on Node 14. Not sure if I'm doing something wrong here?

node: `node14-slim`
package: `"@google-cloud/monitoring": "^2.3.3"`

```
/usr/src/app/node_modules/protobufjs/src/namespace.js:383
        throw Error("no such type: " + path);
        ^

Error: no such type: google.monitoring.v3.CreateTimeSeriesSummary
    at Root.lookupType (/usr/src/app/node_modules/protobufjs/src/namespace.js:383:15)
    at GoogleErrorDecoder.decodeProtobufAny (/usr/src/app/node_modules/google-gax/build/src/googleError.js:38:32)
    at /usr/src/app/node_modules/google-gax/build/src/googleError.js:74:82
    at Array.map (<anonymous>)
    at /usr/src/app/node_modules/google-gax/build/src/googleError.js:74:63
    at Array.forEach (<anonymous>)
    at GoogleErrorDecoder.decodeRpcStatusDetails (/usr/src/app/node_modules/google-gax/build/src/googleError.js:71:19)
    at Immediate.callback (/usr/src/app/node_modules/google-gax/build/src/call.js:89:49)
    at processImmediate (internal/timers.js:466:21)
```

```
const monitoring = require('@google-cloud/monitoring');

const monitoringClient = new monitoring.MetricServiceClient({
  projectId: 'my-project-id',
  credentials: require('../gcpServiceAccount.json'),
});

// ...

monitoringClient.createTimeSeries(request);
```

**Comment by stx** [comment]
Downgrading to @google-cloud/monitoring 1.5.0 works correctly, prior to the package migrating to CreateTimeSeriesSummary.

**Comment by SurferJeffAtGoogle** [comment]
I copied your code into this project:
https://github.com/SurferJeffAtGoogle/scratch/blob/master/issue566/test/make-time-series.ts

It compiles without error.  Of course the test fails without a project id or service account file.

Have you tried running `npm run ci`?

Please create a pull request modifying that project that reproduces your error.

**Comment by stx** [comment]
I'm not able to reproduce it following a reboot... no clue. Sorry!

**Comment by 8lueberry** [comment]
I also get this error on `2.3.3` and it compiles without error, it's when it's running, seems like there's some async calls that fail

I have a similar stack as @stx

```
[server] ERROR [2021-08-16 17:20:10]: (app) UncaughtException
[server]     code: "CODE"
[server]     resolution: "Make sure all async calls are try/catch"
[server]     err: {
[server]       "type": "Error",
[server]       "message": "no such type: google.monitoring.v3.CreateTimeSeriesSummary",
[server]       "stack":
[server]           Error: no such type: google.monitoring.v3.CreateTimeSeriesSummary
[server]               at Root.lookupType (/Users/dan/Code/narative/fey/node_modules/protobufjs/src/namespace.js:383:15)
[server]               at GoogleErrorDecoder.decodeProtobufAny (/Users/dan/Code/narative/fey/node_modules/@google-cloud/monitoring/node_modules/google-gax/build/src/googleError.js:38:32)
[server]               at /Users/dan/Code/narative/fey/node_modules/@google-cloud/monitoring/node_modules/google-gax/build/src/googleError.js:74:82
[server]               at Array.map (<anonymous>)
[server]               at /Users/dan/Code/narative/fey/node_modules/@google-cloud/monitoring/node_modules/google-gax/build/src/googleError.js:74:63
[server]               at Array.forEach (<anonymous>)
[server]               at GoogleErrorDecoder.decodeRpcStatusDetails (/Users/dan/Code/narative/fey/node_modules/@google-cloud/monitoring/node_modules/google-gax/build/src/googleError.js:71:19)
[server]               at Immediate.callback (/Users/dan/Code/narative/fey/node_modules/@google-cloud/monitoring/node_modules/google-gax/build/src/call.js:89:49)
[server]               at processImmediate (internal/timers.js:458:21)
[server]               at process.topLevelDomainCallback (domain.js:137:15)
[server]     }
[server] UncaughtException
[server] Error: no such type: google.monitoring.v3.CreateTimeSeriesSummary
[server]     at Root.lookupType (/Users/dan/Code/narative/fey/node_modules/protobufjs/src/namespace.js:383:15)
[server]     at GoogleErrorDecoder.decodeProtobufAny (/Users/dan/Code/narative/fey/node_modules/@google-cloud/monitoring/node_modules/google-gax/build/src/googleError.js:38:32)
[server]     at /Users/dan/Code/narative/fey/node_modules/@google-cloud/monitoring/node_modules/google-gax/build/src/googleError.js:74:82
[server]     at Array.map (<anonymous>)
[server]     at /Users/dan/Code/narative/fey/node_modules/@google-cloud/monitoring/node_modules/google-gax/build/src/googleError.js:74:63
[server]     at Array.forEach (<anonymous>)
[server]     at GoogleErrorDecoder.decodeRpcStatusDetails (/Users/dan/Code/narative/fey/node_modules/@google-cloud/monitoring/node_modules/google-gax/build/src/googleError.js:71:19)
[server]     at Immediate.callback (/Users/dan/Code/narative/fey/node_modules/@google-cloud/monitoring/node_modules/google-gax/build/src/call.js:89:49)
[server]     at processImmediate (internal/timers.js:458:21)
[server]     at process.topLevelDomainCallback (domain.js:137:15)
```
